- name: 下载filebeat解压并重命名
  shell: |
     cd /tmp/
     wget http://47.105.80.198:8080/elk/filebeat/filebeat-6.2.4-linux-x86_64.tar.gz
     tar zxvf filebeat-6.2.4-linux-x86_64.tar.gz
     mv filebeat-6.2.4-linux-x86_64   /usr/local/filebeat
     rm -rf filebeat-6.2.4-linux-x86_64.tar.gz
- name: 上传filebeat.service
  copy:
    src: filebeat.service
    dest:   /usr/lib/systemd/system/filebeat.service
- name: 写入system服务
  shell: systemctl daemon-reload 

