- name: 下载logstash解压并重命名
  shell: |
    cd /tmp/
    wget http://10.30.0.50:8080/elk/logstash/logstash-6.2.4.tar.gz
    tar zxvf logstash-6.2.4.tar.gz
    mv logstash-6.2.4    /usr/local/logstash
    mkdir -p /usr/local/logstash/config/conf.d
    rm -rf logstash-6.2.4.tar.gz
- name: 下载logstash.service
  shell: | 
    cd /tmp/
    wget http://10.30.0.50:8080/elk/logstash/logstash.service
    mv -f logstash.service  /usr/lib/systemd/system/
- name: 写入system服务
  shell: systemctl daemon-reload 

