- name: 下载logstash解压并重命名
  shell: |
    cd /tmp/
    wget http://47.105.80.198:8080/elk/logstash/logstash-6.2.4.tar.gz
    tar zxvf logstash-6.2.4.tar.gz
    mv logstash-6.2.4    /usr/local/logstash
    mkdir -p /usr/local/logstash/config/conf.d
    rm -rf logstash-6.2.4.tar.gz
- name: 下载logstash.service
  copy:
    src: logstash.service
    dest:  /usr/lib/systemd/system/logstash.service
- name: 写入system服务
  shell: systemctl daemon-reload 

