---
- hosts : test
  tasks:
     - name : 修改时区
       shell : " ln -sf  /usr/share/zoneinfo/Asia/Shanghai /etc/localtime "
  #tasks:
     #- name : 重启机器
      # shell : " reboot "
  tasks:
     - name : 安装ntp服务
       shell : " yum install ntp -y "
  tasks:
     - name : 同步时间
       shell :  "ntpdate  cn.pool.ntp.org"


  
