---
- hosts : test
  #vars :  
      #touch_file : 111.txt
  tasks:
     - name : 根据系统文件来创建文件
       command : "touch /tmp/this_is_{{ansible_distribution}}_system" 
       when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" ) or
             (ansibel_distribution == "Debian" and ansible_distribution_major_version == "7")
