kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: /etc/kubernetes/kube-proxy.kubeconfig
clusterCIDR: 10.254.0.0/16
hostnameOverride: {{ hostvars[inventory_hostname].ansible_ssh_host }}
mode: "ipvs"