- name: 执行解压以及安装
  unarchive: src=/opt/elk/kafka/kafka_2.10-0.10.1.1.tgz    dest=/usr/local
- name: 重命名
  shell: mv /usr/local/kafka_2.10-0.10.1.1    /usr/local/kafka
- name: 上传kafka.service
  copy:
    src: /opt/elk/kafka/kafka.service
    dest: /usr/lib/systemd/system/
    #force: yes
- name: 写入system服务
  shell: systemctl daemon-reload

