- name: 下载kibana解压并重命名
  shell: |
    cd /tmp/
    wget http://47.105.80.198:8080/elk/kibana/kibana-6.2.4-linux-x86_64.tar.gz
    tar zxvf kibana-6.2.4-linux-x86_64.tar.gz
    mv kibana-6.2.4-linux-x86_64    /usr/local/kibana
    rm -rf kibana-6.2.4-linux-x86_64.tar.gz
- name: 上传kibana.service
  copy:
    src: kibana.service
    dest: /usr/lib/systemd/system/kibana.service
- name: 写入system服务
  shell: systemctl daemon-reload 

