- name: 更新logstash配置
  synchronize:
    src: /opt/elk/logstash/
    dest: /usr/local/logstash/config/conf.d
    delete: yes
    recursive: yes


- name: 重启logstash服务
  systemd:
    state: restarted
    name: logstash

