- name: 下载es解压并重命名 
  shell: |
    cd /tmp/
    wget http://10.30.0.50:8080/elk/es/elasticsearch-6.2.4.tar.gz
    tar zxvf elasticsearch-6.2.4.tar.gz
    mv elasticsearch-6.2.4    /usr/local/elasticsearch
    rm -rf elasticsearch-6.2.4.tar.gz
    useradd elasticsearch
    chown -R elasticsearch:elasticsearch /usr/local/elasticsearch

- name: 下载elasticsearch.service
  shell: |
    cd /tmp/
    wget http://10.30.0.50:8080/elk/es/elasticsearch.service
    mv -f elasticsearch.service  /usr/lib/systemd/system/
- name: 写入system服务
  shell: systemctl daemon-reload 

