- name : 下载文件并解压
  shell: cd /tmp/ && wget http://10.30.0.50:8080/elk/jdk/jdk-8u181-linux-x64.tar.gz  && tar zxvf jdk-8u181-linux-x64.tar.gz && mv jdk1.8.0_181   /usr/local  && rm -rf jdk-8u181-linux-x64.tar.gz
- name: 执行环境变量使其生效
  shell: cd /tmp/ && wget http://10.30.0.50:8080/elk/jdk/profile              mv -f ./profile   /etc/profile && source /etc/profile && java -version

