- name: 更新es配置
  synchronize:
    src: /opt/elk/es/
    dest: /usr/local/elasticsearch/config
    delete: yes
    recursive: yes


- name: 重启es服务
  systemd:
    state: restarted
    name: elasticsearch

